// <auto-generated />
using System;
using EF_CODE_FIRST_FINAL_ASSIGNMENT.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_CODE_FIRST_FINAL_ASSIGNMENT.Migrations
{
    [DbContext(typeof(FinalAssignmentContext))]
    partial class FinalAssignmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.ChiTietSp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("GiaNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("IdDongSp")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMauSac")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNsx")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSp")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NamBh")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDongSp");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdNsx");

                    b.HasIndex("IdSp");

                    b.ToTable("ChiTietSP");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d79adf9-5af8-400b-b002-de9c77e91715"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/247364/samsung-galaxy-m53-nau-thumb-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a2"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            NamBh = 2002,
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("0ae9ee50-64d7-4693-b989-d9d72422cb4c"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/230529/TimerThumb/iphone-13-pro-max-(18).jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a8"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            NamBh = 2002,
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("5bc44e58-77ae-49b8-8bf2-242c4a0296fc"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/251703/oppo-a95-4g-bac-2-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a9"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            NamBh = 2002,
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("0216511a-4656-400f-8f3a-1c013bf179bd"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/253402/realme-c21-y-blue-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a9"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            NamBh = 2002,
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("c6103363-29ab-438f-9d7d-d9fc9ba4cdc9"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/247364/samsung-galaxy-m53-nau-thumb-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a5"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            NamBh = 2002,
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("fbfd3d45-a92a-49bd-a2e4-aabeac6be899"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/247364/samsung-galaxy-m53-nau-thumb-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a6"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            NamBh = 2002,
                            SoLuongTon = 50
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChucVu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a7"),
                            Ma = "NV1",
                            Ten = "Trần Nam"
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.CuaHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CuaHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a8"),
                            Ma = "CH1",
                            Ten = "Minky Store"
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.DongSp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("DongSP");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            Ma = "DSP1",
                            Ten = "Iphone"
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DonGiaKhiGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdGioHang", "IdChiTietSp");

                    b.HasIndex("IdChiTietSp");

                    b.ToTable("GioHangChiTiet");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IdKh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("NgayShip")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("DATE");

                    b.Property<string>("Sdt")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IdKh");

                    b.HasIndex("IdNv");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdHoaDon", "IdChiTietSp");

                    b.HasIndex("IdChiTietSp");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ho")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ma")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("DATE");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenDem")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5018e9f5-42bd-456b-8ba8-2e29d42a5115"),
                            Ma = "KH1",
                            NgaySinh = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ten = "Ánh"
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a2"),
                            Ma = "MS1",
                            Ten = "Đỏ"
                        },
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a8"),
                            Ma = "MS1",
                            Ten = "Vàng"
                        },
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a9"),
                            Ma = "MS1",
                            Ten = "Tím"
                        },
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a5"),
                            Ma = "MS1",
                            Ten = "Trắng"
                        },
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a6"),
                            Ma = "MS1",
                            Ten = "Đen"
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ho")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("IdCh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGuiBc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("DATE");

                    b.Property<string>("Sdt")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenDem")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IdCh");

                    b.HasIndex("IdCv");

                    b.HasIndex("IdGuiBc");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6931724-bc54-4d27-a720-88d972f1e5f2"),
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            Ho = "Nguyễn",
                            IdCh = new Guid("b29ceea6-16a5-4171-9486-621650b569a8"),
                            IdCv = new Guid("b29ceea6-16a5-4171-9486-621650b569a7"),
                            Ma = "NV1",
                            MatKhau = "1234",
                            NgaySinh = new DateTime(2022, 8, 15, 16, 7, 49, 963, DateTimeKind.Local).AddTicks(914),
                            Sdt = "1234",
                            Ten = "Đăng",
                            TenDem = "Viết Hải",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.Nsx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Nsx");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            Ma = "DSP1",
                            Ten = "Apple"
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ma")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            Ma = "SP1",
                            Ten = "Iphone 13 Promax"
                        });
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.ChiTietSp", b =>
                {
                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.DongSp", "DongSp")
                        .WithMany("ChiTietSps")
                        .HasForeignKey("IdDongSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.MauSac", "MauSac")
                        .WithMany("ChiTietSps")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.Nsx", "Nsx")
                        .WithMany("ChiTietSps")
                        .HasForeignKey("IdNsx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.SanPham", "SanPham")
                        .WithMany("ChiTietSps")
                        .HasForeignKey("IdSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DongSp");

                    b.Navigation("MauSac");

                    b.Navigation("Nsx");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.GioHang", b =>
                {
                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.KhachHang", "KhachHang")
                        .WithMany("GioHangs")
                        .HasForeignKey("KhachHangId");

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.NhanVien", "NhanVien")
                        .WithMany("GioHangs")
                        .HasForeignKey("NhanVienId");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.GioHangChiTiet", b =>
                {
                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.ChiTietSp", "ChiTietSp")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdChiTietSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSp");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.HoaDon", b =>
                {
                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKh");

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNv");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.HoaDonChiTiet", b =>
                {
                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.ChiTietSp", "ChiTietSp")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSp");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.NhanVien", b =>
                {
                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.CuaHang", "CuaHang")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCh");

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCv");

                    b.HasOne("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.NhanVien", "Nhan_Vien")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdGuiBc");

                    b.Navigation("ChucVu");

                    b.Navigation("CuaHang");

                    b.Navigation("Nhan_Vien");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.ChiTietSp", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.CuaHang", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.DongSp", b =>
                {
                    b.Navigation("ChiTietSps");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.KhachHang", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.MauSac", b =>
                {
                    b.Navigation("ChiTietSps");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.NhanVien", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.Nsx", b =>
                {
                    b.Navigation("ChiTietSps");
                });

            modelBuilder.Entity("EF_CODE_FIRST_FINAL_ASSIGNMENT.DomainClass.SanPham", b =>
                {
                    b.Navigation("ChiTietSps");
                });
#pragma warning restore 612, 618
        }
    }
}
