// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinkyShop.Infrastructure.Data;

#nullable disable

namespace MinkyShop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.ChiTietSp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("GiaNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("IdDongSp")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMauSac")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNsx")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDongSp");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdNsx");

                    b.HasIndex("IdSp");

                    b.ToTable("ChiTietSp");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4541a279-9813-4ce2-bdc2-d5cdca240d13"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/247364/samsung-galaxy-m53-nau-thumb-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a2"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("d0397c42-9a13-44b0-9a69-34a278d0f3eb"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/230529/TimerThumb/iphone-13-pro-max-(18).jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a8"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("b259d5e3-64b1-4276-a7dc-c7953a019bd1"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/251703/oppo-a95-4g-bac-2-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a9"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("21ea1339-27c9-4008-b49a-792da2ac24b6"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/253402/realme-c21-y-blue-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a9"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("266ebcec-a9ae-4c5e-9988-b37e522c3d64"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/247364/samsung-galaxy-m53-nau-thumb-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a5"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            SoLuongTon = 50
                        },
                        new
                        {
                            Id = new Guid("7273e040-d365-4be5-b65e-8da92667f5db"),
                            Anh = "https://cdn.tgdd.vn/Products/Images/42/247364/samsung-galaxy-m53-nau-thumb-600x600.jpg",
                            GiaBan = 200000m,
                            GiaNhap = 900000m,
                            IdDongSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            IdMauSac = new Guid("b29ceea6-16a5-4171-9486-621650b569a6"),
                            IdNsx = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            IdSp = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            MoTa = "",
                            SoLuongTon = 50
                        });
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.DongSp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("DongSp");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a1"),
                            Ten = "Iphone"
                        });
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdKh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("NgayShip")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("DATE");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("IdKh");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdHoaDon", "IdChiTietSp");

                    b.HasIndex("IdChiTietSp");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a2"),
                            Ten = "Đỏ"
                        },
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a8"),
                            Ten = "Vàng"
                        },
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a9"),
                            Ten = "Tím"
                        },
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a5"),
                            Ten = "Trắng"
                        },
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a6"),
                            Ten = "Đen"
                        });
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.NguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ho")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("DATE");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenDem")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.Nsx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Nsx");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a3"),
                            Ten = "Apple"
                        });
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29ceea6-16a5-4171-9486-621650b569a4"),
                            Ten = "Iphone 13 Promax"
                        });
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.ChiTietSp", b =>
                {
                    b.HasOne("MinkyShop.Infrastructure.Data.Entities.DongSp", "DongSp")
                        .WithMany("ChiTietSps")
                        .HasForeignKey("IdDongSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinkyShop.Infrastructure.Data.Entities.MauSac", "MauSac")
                        .WithMany("ChiTietSps")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinkyShop.Infrastructure.Data.Entities.Nsx", "Nsx")
                        .WithMany("ChiTietSps")
                        .HasForeignKey("IdNsx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinkyShop.Infrastructure.Data.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietSps")
                        .HasForeignKey("IdSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DongSp");

                    b.Navigation("MauSac");

                    b.Navigation("Nsx");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.HoaDon", b =>
                {
                    b.HasOne("MinkyShop.Infrastructure.Data.Entities.NguoiDung", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKh");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("MinkyShop.Infrastructure.Data.Entities.ChiTietSp", "ChiTietSp")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinkyShop.Infrastructure.Data.Entities.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSp");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.ChiTietSp", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.DongSp", b =>
                {
                    b.Navigation("ChiTietSps");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.MauSac", b =>
                {
                    b.Navigation("ChiTietSps");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.NguoiDung", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.Nsx", b =>
                {
                    b.Navigation("ChiTietSps");
                });

            modelBuilder.Entity("MinkyShop.Infrastructure.Data.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietSps");
                });
#pragma warning restore 612, 618
        }
    }
}
